id: P006725
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:19:24.900024
source_metadata:
  id: bdr:W20325
  title: རྙིང་མ་བའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    c3955e64de77420c82be3713e9dda5ce:
      image_group_id: I4245
      title: ''
      volume_number: 1
      total_pages: 716
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
